name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu runner

    steps:
      # Checkout the code from your GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use the required Python version, you can change it

      # Install dependencies (ensure you have a requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (if you have tests for your app, for example using pytest)
      - name: Run tests
        run: |
          # If you don't have tests, you can skip this step
          pytest  # Replace with your testing framework or script if different

      # Run the Python app (you can skip this if you only want testing)
      - name: Run BMI Calculator App
        run: |
          python "# BMI Calculator App.py"  # Or `python bmi_calculator_app.py` if you rename it
